package de.oopexpert.oopdi.proxy;

import java.util.function.Supplier;

/**
 * Implemented by every Byte Buddy proxy class generated by {@link ByteBuddyProxyFactory}.
 * Carries the per-proxy interception state (owning container's request-scope manager and the
 * supplier for the real object), so that generated proxy <em>classes</em> can be shared across
 * containers while every proxy <em>instance</em> still resolves through its own container.
 *
 * <p>Framework-internal plumbing (like {@code InternalResolutionContext}): not part of the
 * public API contract.</p>
 */
public interface ProxiedBeanCarrier {

	void oopdi$init(ProxyTarget target);

	ProxyTarget oopdi$target();

}
