name: Release Pipeline

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tag
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build application
        env:
          dbUrl: "jdbc://mysql:userdb"
        working-directory: oopdi
        run: mvn clean package --file pom.xml -DdbUsername=dbUser1 -Dcounter=4

      - name: Create GitHub Release and upload artifact
        run: gh release create "${{ github.ref_name }}" oopdi/target/*.jar --title "${{ github.ref_name }}" --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
